# Download old binary
- name: Install teleport
  apt: 
    deb: "https://get.gravitational.com/teleport_{{ teleport_version | default('8.0.7') }}_amd64.deb"
  become: true


- name: reload the service
  systemd:
    state: reloaded
    name: teleport
  become: true