# Download old binary
- name: Install teleport
  apt: 
    deb: "https://get.gravitational.com/teleport_{{ teleport_version | default('8.0.7') }}_amd64.deb"
  become: true


# For Manual Install
# - name: Locate Teleport Process PID
#   command: pidof teleport
#   become: true
#   register: teleport_pid

# - name: PID of current process
#   debug: "teleport PID {{ teleport_parent_pid.stdout }}"

# - name: Rename old binary 
#   command: "mv /usr/bin/teleport /usr/bin/teleport.bak"
#   become: true

# # Start Upgrade
# - name: "Move new binary to /usr/bin directory"
#   command: cp /tmp/teleport /usr/bin/teleport

# - name: "Fork a new Teleport Process"
#   command: kill -USR2 $(pidof teleport)

# - name: Locate Teleporta all PID
#   command: pidof teleport
#   become: true
#   register: teleport_pid_all

# - name: PID of all teleport process
#   debug: "teleport PIDs {{ teleport_pid_all.stdout }}"

# - name: Write output of last 1000 lines in log to tmp file
#   command: tail -1000  /var/log/teleport/teleport.log > /tmp/teleport-upgrade-logs

# # Post Upgrade Checking
# - name: Check fork is success - Check 1
#   wait_for:
#     path: /tmp/teleport-upgrade-logs
#     search_regex: "INFO Forked new child process"
#     sleep: 5
#     timeout: 60

# - name: Check fork is success - Check 2
#   wait_for:
#     path: /tmp/teleport-upgrade-logs
#     search_regex: "passed by the parent process"
#     sleep: 5
#     timeout: 60

# # Finilizing Upgrade
# - name: Pause for user acknowledgement
#   pause:
#     seconds: 30
#     prompt: Please acknowledge to proceed with killing old process

# - name: Kill old process
#   command: "kill -QUIT {{ teleport_parent_pid.stdout }}"

# - name: Wait for graceful shutdown
#   wait_for:
#     timeout: 60

# - name: Locate Teleport Process PID
#   command: pidof teleport
#   become: true
#   register: teleport_new_pid

# - name: PID of new process
#   debug: "Old process is not killed"
#   when: teleport_new_pid.stdout == teleport_parent_pid.stdout

# - name: Ungraceful kill of old process
#   command: "kill -TERM {{ teleport_parent_pid.stdout }}"
#   when: teleport_new_pid.stdout == teleport_parent_pid.stdout