- name: Make sure node_type is allowed
  fail:
    msg: >-
      node_type "{{ node_type }}" is not allowed.
      Please choose a target environment in {{ node_type | join(', ') }}
  when: not node_type in _allowed_node_type
  vars:
    _allowed_node_type:
      - main_proxy
      - main_auth
      - leaf
      - ssh
      - k8s
      - application
  run_once: true

- name: Create AWS dir
  file:
    path: /home/teleport/.aws
    owner: teleport
    group: teleport
    state: directory
    mode: '0766'
  become: true
  when: node_type in ['main_auth', 'leaf']

- name: Copy AWS Creds
  template:
    src: "credentials.j2"
    dest: "/home/teleport/.aws/credentials"
    owner: teleport
    group: teleport
    mode: 0600
  become: true
  when: node_type in ['main_auth', 'leaf']

- name: Copy teleport to /etc/teleport.yaml
  template:
    src: "teleport.yaml.j2"
    dest: "/etc/teleport.yaml"
    owner: teleport
    group: teleport
    mode: 0600
  become: true

- name: Copy trusted_cluster Config
  template:
    src: "trusted_cluster.yaml.j2"
    dest: "{{ data_dir }}/trusted_cluster.yaml"
    owner: teleport
    group: teleport
    mode: 0600
  become: true
  when: node_type in ['leaf']
 
- name: Restart service teleport
  service:
    name: teleport
    state: restart
  become: true
  
- name: apply leaf configuration
  command: "tctl create {{ data_dir }}/trusted_cluster.yaml"
  become: true
  become_user: teleport
