- name: Make sure node_type is allowed
  fail:
    msg: >-
      node_type "{{ node_type }}" is not allowed.
      Please choose a target environment in {{ node_type | join(', ') }}
  when: not node_type in _allowed_node_type
  vars:
    _allowed_node_type:
      - main_proxy
      - main_auth
      - leaf
      - ssh
      - k8s
      - application
  run_once: true

- name: "Copy teleport license file"
  copy:
    src: "{{ auth_node.copy_license_from_local_file.local_path }}"
    dest: "{{ auth_node.license_file }}"
    owner: teleport
    group: teleport
    mode: 0600
  become: true
  when: auth_node.copy_license_from_local_file is defined and auth_node.copy_license_from_local_file.enable

- name: Set AWS Creds as ENV
  template:
    src: "teleport-env.j2"
    dest: "/etc/default/teleport"
    owner: root
    group: root
    mode: 0600
  become: true
  when: node_type in ['main_auth', 'leaf']

- name: Modify EnvironmentFile param for teleport service
  lineinfile:
    path: "/lib/systemd/system/teleport.service"
    insertafter: '^[Service].*$'
    line: "EnvironmentFile=-/etc/default/teleport"
  become: true
  when: node_type in ['main_auth', 'leaf']

- name: Copy teleport to /etc/teleport.yaml
  template:
    src: "teleport.yaml.j2"
    dest: "/etc/teleport.yaml"
    owner: teleport
    group: teleport
    mode: 0600
  become: true

- name: Copy trusted_cluster Config
  template:
    src: "trusted_cluster.yaml.j2"
    dest: "{{ data_dir }}/trusted_cluster.yaml"
    owner: teleport
    group: teleport
    mode: 0600
  become: true
  when: node_type in ['leaf']
 
- name: Restart service teleport
  systemd:
    daemon_reload: true
    state: restarted
    name: teleport
  become: true
  
- name: apply leaf configuration
  command: "tctl create {{ data_dir }}/trusted_cluster.yaml"
  become: true
  when: node_type in ['leaf']

- name: register ssh_node for node_type main_auth and leaf
  debug: "Now I will register ssh_node for node_type main_auth and leaf"
  when: node_type in ['main_auth', 'leaf'] 

- name: Generate shortlive token
  command: tctl tokens add --type=node --ttl=5m
  become: true
  when: node_type in ['main_auth', 'leaf']
  register: join_token

- name: "Setting auto generating config values into Ansible Fact"
  set_fact:
    auto_generated_auth_token: "{{ join_token.stdout | regex_search('token=(.+) ', '\\1') | first }}"
    auto_generated_ca_pin: "{{ join_token.stdout | regex_search('ca-pin=(.+) ', '\\1') | first }}"
    auto_generated_auth_server: "{{ join_token.stdout | regex_search('auth-server=(.+)', '\\1') | first }}"
  when: node_type in ['main_auth', 'leaf']

- name: Copy teleport to /etc/teleport.yaml
  template:
    src: "teleport.yaml.j2"
    dest: "/etc/teleport.yaml"
    owner: teleport
    group: teleport
    mode: 0600
  become: true
  when: node_type in ['main_auth', 'leaf']

- name: Restart service teleport
  systemd:
    daemon_reload: true
    state: restarted
    name: teleport
  become: true
  when: node_type in ['main_auth', 'leaf']