- name: Make sure node_type is allowed
  fail:
    msg: >-
      node_type "{{ node_type }}" is not allowed.
      Please choose a target environment in {{ node_type | join(', ') }}
  when: not node_type in _allowed_node_type
  vars:
    _allowed_node_type:
      - main_proxy
      - main_auth
      - leaf
      - ssh
      - k8s
      - application
  run_once: true

- name: Set AWS Creds as ENV
  template:
    src: "teleport-env.j2"
    dest: "/etc/default/teleport"
    owner: root
    group: root
    mode: 0600
  become: true
  when: node_type in ['main_auth', 'leaf']

- name: Modify EnvironmentFile param for teleport service
  lineinfile:
    path: "/lib/systemd/system/teleport.service"
    insertafter: '^[Service].*$'
    line: "EnvironmentFile=-/etc/default/teleport"
  become: true

- name: Copy teleport to /etc/teleport.yaml
  template:
    src: "teleport.yaml.j2"
    dest: "/etc/teleport.yaml"
    owner: teleport
    group: teleport
    mode: 0600
  become: true

- name: Copy trusted_cluster Config
  template:
    src: "trusted_cluster.yaml.j2"
    dest: "{{ data_dir }}/trusted_cluster.yaml"
    owner: teleport
    group: teleport
    mode: 0600
  become: true
  when: node_type in ['leaf']
 
- name: Restart service teleport
  systemd:
    daemon_reload: true
    state: restarted
    name: teleport
  become: true
  
- name: apply leaf configuration
  command: "tctl create {{ data_dir }}/trusted_cluster.yaml"
  become: true
  when: node_type in ['leaf']
