- name: Create 'teleport' user
  user:
    name: teleport
    comment: Teleport User
    uid: 1010
  become: true

- name: Install teleport
  apt: 
    deb: "https://get.gravitational.com/teleport_{{ teleport_version | default('7.3.2') }}_amd64.deb"
  become: yes

- name: Create teleport dirs
  file:
    path: "{{ item }}"
    owner: teleport
    group: teleport
    state: directory
    mode: '0750'
  loop:
    - "/var/log/teleport"
    - "/var/lib/teleport"
  become: yes

- name: Modify hard/soft nofile limits for teleport
  community.general.pam_limits:
    domain: 'teleport'
    limit_type: '-'
    limit_item: nofile
    value: 1065536
  become: yes
   
- name: Modify hard nproc limits for teleport
  community.general.pam_limits:
    domain: 'teleport'
    limit_type: '-'
    limit_item: nproc
    value: 1065536
  become: yes
