- name: Add Teleport Key
  apt_key:
    url: https://deb.releases.teleport.dev/teleport-pubkey.asc
    state: presen
  become: yes
    
- name: Add repo to APT
  apt_repository:
    repo: deb https://deb.releases.teleport.dev/ stable main
    state: present
  become: yes

- name: Install teleport
  apt: 
    update_cache: true
    name: teleport
    state: present
  become: yes

- name: Create teleport dirs
  file:
    path: {{ item }}
    owner: teleport
    group: teleport
    state: directory
    mode: '0750'
  loop:
    - "/var/log/teleport"
    - "/var/lib/teleport"
   become: yes

- name: Modify hard/soft nofile limits for teleport
  community.general.pam_limits:
    domain: 'teleport'
    limit_type: '-'
    limit_item: nofile
    value: 1065536

- name: Modify hard nproc limits for teleport
  community.general.pam_limits:
    domain: 'teleport'
    limit_type: '-'
    limit_item: nproc
    value: 1065536
