- name: Create 'teleport' user
  user:
    name: teleport
    comment: Teleport User
    uid: 1010
  become: true

- name: Install teleport
  apt: 
    deb: "https://get.gravitational.com/teleport_{{ teleport_version | default('7.3.2') }}_amd64.deb"
  become: true

- name: Create teleport dirs
  file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
    mode: '0750'
  loop:
    - "/var/log/teleport"
    - "/var/lib/teleport"
  become: true

- name: Modify LimitNOFILE for teleport
  lineinfile:
    path: "/lib/systemd/system/teleport.service"
    regexp: '^LimitNOFILE=.*$'
    line: "LimitNOFILE=65536"
  become: true

- name: reload the service
  systemd:
    daemon_reload: true
    state: started
    name: teleport
  become: true